### ISSUE TITLE
boolean isGreater = myCalculator.isGreater(12.0, 25.0);

### ISSUE THREAD

**Issue by tallinn-learning** [VeronikaOstrovski/homerwork04#1]
https://github.com/VeronikaOstrovski/homerwork04/blob/01afabd0fcf33664ad3ce35ee3a50688d9d0d633/src/CalcMain.java#LL7C2-L7C2

**Comment by VeronikaOstrovski** [comment]
А почему myCalculator? У меня же класс называется "Calculator"......

**Comment by tallinn-learning** [comment]
верно подмечено, экземпляр (не класс) называется сalculator
